# Application configuration
## Warning: Set debug to true only during development & debugging!
##          Make sure debug is false on production!
debug=true

## Test-related configuration
app.test.browser=chrome

## Database-related configuration
spring.jpa.databasePlatform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/eshop
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driverClassName=org.postgresql.Driver
